services:
  # backendはまだ仮
  # backend:
  #   build:
  #     context: ./backend/
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./backend:/app
  #   depends_on:
  #     - db
  frontend:
    build:
      context: ./Epic_frontend/
      dockerfile: Dockerfile
    volumes:
      - ./Epic_frontend:/app
    ports:
      - 3000:3000
  # dbもまだ仮
  # db:
  #   image: "postgres:15-alpine"
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=db
  #   volumes:
  #     - db-store:/var/lib/postgresql/data
